sonar.projectKey=microservicio-produccion-cocina
sonar.projectName=Microservicio Produccion Cocina
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.language=php
sonar.sourceEncoding=UTF-8

sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,database/**
sonar.test.exclusions=vendor/**,tests/**

sonar.php.coverage.reportPaths=coverage.xml

# Incluir archivos JavaScript/TypeScript
sonar.inclusions=**/*.php,**/*.js,**/*.ts

# Cobertura de código
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
